name: Push a Docker hub y deploy con CloudFormation

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Inicia sesion en docker hub
      run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin 
    - name: Construye la imagen usando el Dockerfile
      run: docker build . --file Dockerfile --tag hipermegared/inventario:latest    
    
